// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMlH-C1xjQuBhAXXEzqL8okxStgHW1otA',
    appId: '1:195562948568:web:9b0c7843caeab3300d54ad',
    messagingSenderId: '195562948568',
    projectId: 'my-first-firebase-projec-7cf3a',
    authDomain: 'my-first-firebase-projec-7cf3a.firebaseapp.com',
    storageBucket: 'my-first-firebase-projec-7cf3a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl_s_truoI3wXi5_vCw79N4wah4gojitM',
    appId: '1:195562948568:android:26c7703de82d17ae0d54ad',
    messagingSenderId: '195562948568',
    projectId: 'my-first-firebase-projec-7cf3a',
    storageBucket: 'my-first-firebase-projec-7cf3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL4gXSQzBxEpZtjcCrqkULzjoippwzzxA',
    appId: '1:195562948568:ios:2419a745ae6d3fb20d54ad',
    messagingSenderId: '195562948568',
    projectId: 'my-first-firebase-projec-7cf3a',
    storageBucket: 'my-first-firebase-projec-7cf3a.firebasestorage.app',
    iosBundleId: 'com.example.margin',
  );
}
